# GitLab CI — Secrets Detection Only

stages:
  - secrets

variables:
  SECUREPIPE_OUTPUT: "securepipe-reports"

gitleaks:
  stage: secrets
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  script:
    - gitleaks detect --source . --report-format json --report-path ${SECUREPIPE_OUTPUT}/secrets-results.json || true
  artifacts:
    paths:
      - ${SECUREPIPE_OUTPUT}/
    expire_in: 30 days